# Site settings
title: Lukas Hajdu
email: me@lukashajdu.com
description: "I'm Lukas Hajdu, web weveloper, programmer with 5+ years of experience in field"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 199ABD
  secondary: 2c3e50
  secondary-dark: 233140

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/lhajdu
  - title: stack-overflow
    url: http://stackoverflow.com/users/2889514/lukas-hajdu
  - title: bitbucket 
    url: https://bitbucket.org/lukashajdu/
  - title: github
    url: https://github.com/lukashajdu

# Postal address (add as many lines as necessary)
address:
  - line: London

# Build settings
markdown: kramdown
permalink: pretty
